# ObsidianDestoyer by drtshock and squidicuzz
# For information and updates visit http://dev.bukkit.org/server-mods/ObsidianDestroyer
# Join irc for live support http://webchat.esper.net/?channels=drtshock&prompt=1
# Or use our issue tracker @ https://github.com/drtshock/ObsidianDestroyer/issues

# Made with love <3

# Do not touch this line. It will rewrite your config. 
# The old config will be saved as 'config.yml.old'
Version: ${project.version}

# This will only check for updates and download them by default.
# This plugin does not break between minecraft versions so you should not have an issue updating to the most recent build.
checkupdate: true
downloadupdate: true

# The explosion radius that will be checked. Blocks in this radius will be affected.
# Must be greater than zero and not above ten. Will create lag with high radius
# See 'MATERIAL.BlastRadius' in materials.yml for custom distance.
Radius: 3

# DURABILITY IS NOW IN THE MATERIALS.YML FILE

# Allows the durability of materials to gradually regenerate over time.
# Requires:  'MATERIAL.Durability.ResetEnabled: true'  in materials.yml and adjustment of timings.
# Example Timing Adjustment: 'OBSIDIAN.Durability.ResetAfter: 60000' for obsidian to regenerate 1 durability every minute
DurabilityRegeneratesOverTime: false

# The item used to check the durability of blocks
# Permission node: 'obsidiandestroyer.check'
DurabilityCheckItem: POTATO_ITEM

# Effects that are displayed when materials take damage
Effects:
  Enabled: true
  Chance: 0.12

# False means that water and lava won't protect industructable materials from explosions.
# Only applies if the material is enabled in materials.yml
# This is a fix for the handling of blocks like obsidian that are not normally destroyable,
#  but become destroyed in water with this disabled.
FluidsProtectIndustructables: true

# When bedrock destruction is enabled, this prevents holes into the void...
# HOLY CRAP DON'T TURN THIS OFF
ProtectBedrockBorders: true

# Enables a bypass to allow explosions to affect ALL blocks under / next to liquids.
# This will bypass ALL blocks. We recommend not to use both this AND 'FluidsProtectIndustructables'.
# Destroys fluid blocks and creates a new explosion.
Explosions:
  BypassAllFluidProtection: false

  # Protects "TNT cannons" from being destroyed when used. 
  # This doesn't do anything unless the above option is true.
  TNTCannonsProtected: true

# List of worlds that the plugin will not interact with.
# Example: DisabledOnWorlds: [world_survival, world_creative]
DisabledOnWorlds: []

# Thats it :3