# ObsidianDestoyer by drtshock and squidicuzz
# For information and updates visit http://dev.bukkit.org/server-mods/ObsidianDestroyer
# Join irc for live support http://webchat.esper.net/?channels=drtshock&prompt=1
# Or use our issue tracker @ https://github.com/drtshock/ObsidianDestroyer/issues

# Made with love <3

# Do not touch this line. It will rewrite your config.
Version: ${project.version}

# This will only check for updates by default. You can also enable this to download them for you (I don't recommend this).
# This plugin does not break between minecraft versions so you should not have an issue updating to the most recent build.
# For this to work you need to add your curse api key to /plugins/updater/config.yml
checkupdate: true
downloadupdate: false

# The explosion radius that will affect blocks 
Radius: 3

# The id of the item you use to check durability.
# NO LONGER USED. Can only use a red rose now.
# CheckItemId: 38

# Setting this to true may cause errors with other plugins. But it will make us handle all explosions
# no matter what other plugins try to do.
IgnoreCancel: false
  
# False means that water and lava won't protect industructable materials from explosions.
# This only applies if the material is enabled in materials.yml
FluidsProtectIndustructables: true

# Enables a bypass to allow explosions to affect ALL blocks under / next to liquids.
# This will bypass ALL blocks. We recommend not to use both this AND fluids protect.
Explosions:
  BypassAllFluidProtection: false
  
  # Protects "TNT cannons" from being destroyed when used. 
  # This doesn't do anything unless the above option is true.
  TNTCannonsProtected: true
  
# List of worlds that the plugin will not interact with.
# Example: DisabledOnWorlds: [world_survival, world_creative]
DisabledOnWorlds: []
  
# Thats it :3