name: ObsidianDestroyer
main: com.drtshock.obsidiandestroyer.ObsidianDestroyer
version: ${project.version}-b${BUILD_NUMBER}
authors: [drtshock, squidicuz]
softdepend: [Factions, Towny, WorldGuard]

commands:
    obsidiandestroyer:
        description: ObisidanDestroyer
        usage: |
               /<command>
    od:
        description: ObisidanDestroyer
        usage: |
               /<command>