name: ObsidianDestroyer
main: com.pandemoneus.obsidianDestroyer.ObsidianDestroyer
version: ${project.version}
author: ['drtshock', 'squidicuzz']
softdepend: [Factions]

commands:
    obsidiandestroyer:
        description: ObisidanDestroyer
        usage: |
               /<command>
    od:
        description: ObisidanDestroyer
        usage: |
               /<command>