name: ObsidianDestroyer
main: io.snw.obsidiandestroyer.ObsidianDestroyer
version: ${project.version}
authors: [drtshock, squidicuz]
softdepend: [Factions, Towny, WorldGuard]

commands:
    od:
        description: ObsidianDestroyer command.
        usage: /<command>
        aliases: [obsidiandestroyer]