name: ObsidianDestroyer
main: io.snw.obsidiandestroyer.ObsidianDestroyer
version: ${project.version}
authors: [drtshock, squidicuz]
softdepend: [Factions, Towny, WorldGuard]

commands:
    od:
        description: ObsidianDestroyer command.
        usage: /<command> <reload | reloadDB | reset | version>
        aliases: [obsidiandestroyer]
        permission: obsidiandestroyer.admin
permissions:
    obsidiandestroyer.admin:
      default: op
      description: Allow you to use all admin commands for this plugin.